spring.datasource.url=jdbc:mysql://localhost:3306/Monarch
spring.datasource.username=root
spring.datasource.password=admin
cloudinary.cloud-name=dwfdbgcx4
cloudinary.api-key=411441936246436
cloudinary.api-secret=incT0WWct0uTCAFKphGlp-CdZZI
